[package]
name = "common-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.15.1", features = ["v4"] } # UUID support
serde = { version = "1.0", features = ["derive"] } # Serialization
rocket = { version = "0.5", features = ["json"] }  # Web Server
