[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
rune-client = { path = "../rune-client" }
tokio = { version = "1", features = ["full", "rt-multi-thread"] }  # For async tests
